ES-849698 - Add UG to compare two DOCX in Java - Development
syncfusion-content/java-file-format-docs pull request #142
Opened 2023-11-28 14:14 UTC by KonduruKeerthi

Prepared UG content to compare two word documents in Java

2023-11-28 14:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/879/console)**

2023-11-28 14:15 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/879/)<br/>**

2023-11-29 10:42 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/880/)<br/>**

2023-11-29 10:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/881/console)**

2023-11-29 10:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/881/)<br/>**

2023-11-30 07:05 UTC, MathanKumarVaradhaRajaPerumal requested changes

2023-11-30 07:05 UTC, MathanKumarVaradhaRajaPerumal commented on java-file-formats/word-library/Word-document/Compare-Word-documents.md
> +![Compare Word documents in Java](../WorkingwithWordDocument_images/Compare-Word-documents-without-author.png)
Change images with revision in ballons

2023-11-30 07:05 UTC, MathanKumarVaradhaRajaPerumal commented on java-file-formats/word-library/Word-document/Compare-Word-documents.md
> +You can download a complete working sample from GitHub.
please check and remove

2023-11-30 07:49 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/883/console)**

2023-11-30 07:49 UTC, KonduruKeerthi commented on java-file-formats/word-library/Word-document/Compare-Word-documents.md
> +Compare the existing Word documents or documents created from scratch using the ``Compare`` method in ``WordDocument`` class.
Modified as suggested

2023-11-30 07:50 UTC, KonduruKeerthi commented on java-file-formats/word-library/Word-document/Compare-Word-documents.md
> +originalDocument.close();
Modified as suggested

2023-11-30 07:50 UTC, KonduruKeerthi commented on java-file-formats/word-library/Word-document/Compare-Word-documents.md
> +![Compare Word documents in Java](../WorkingwithWordDocument_images/Compare-Word-documents-without-author.png)
Modified as suggested

2023-11-30 07:50 UTC, KonduruKeerthi commented on java-file-formats/word-library/Word-document/Compare-Word-documents.md
> +You can download a complete working sample from GitHub.
remove the line

2023-11-30 07:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/883/console)**

2023-11-30 07:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-849698-Compare-Word-Documents-Dev](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/883/)<br/>**

2023-11-30 08:28 UTC, MathanKumarVaradhaRajaPerumal approved these changes

2023-12-08 07:07 UTC, MohanaselvamJothi approved these changes

2023-12-08 07:07 UTC, merged