WF-59844-Changed package name
syncfusion-content/java-file-format-docs pull request #89
Opened 2023-03-07 07:56 UTC by elizabethatienoo

<table style="width: 521.306px;">
<tbody>
<tr>
<td style="width: 156px;">Task Link</td>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-59844</td>
</tr>
<tr>
<td style="width: 156px;">Description</td>
<td style="width: 349.306px;">Added package name </td>
</tr>
<tr>
<td style="width: 156px;">Solution</td>
<td style="width: 349.306px;">Added package name in getting started UG page</td>
</tr>
<tr>
<td style="width: 156px;">Content review confirmation</td>
<td style="width: 349.306px;">Pending</td>
</tr>
</tbody>
</table>

2023-03-07 07:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/console)**

2023-03-07 07:59 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/)<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/845/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-07 09:35 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/console)**

2023-03-07 09:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/console)**

2023-03-07 09:44 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/)<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/846/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-10 07:04 UTC, Suriya-Balamurugan requested changes

2023-03-10 07:04 UTC, Suriya-Balamurugan commented on java-file-formats/word-library/getting-started.md
> +import com.synfusion.javahelper.system,.*;
Use import com.syncfusion.javahelper.system.*;

2023-03-10 13:32 UTC, elizabethatienoo commented on java-file-formats/word-library/getting-started.md
> +import com.synfusion.javahelper.system,.*;
Addressed

2023-03-10 13:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/console)**

2023-03-10 13:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WF-59844-Change-package-names](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/java-file-format-docs/849/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-10 14:02 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-03-13 09:14 UTC, MohanaselvamJothi approved these changes

2023-03-13 09:15 UTC, merged